#!/bin/sh
# Prometheus JMX for JWS
set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR="$SCRIPT_DIR/added"

# install prometheus-jmx-exporter
dnf install -y prometheus-jmx-exporter
dnf clean all

# copy the configuration for JWS
mkdir -p /opt/jboss/container/prometheus/etc
cp -p "$ADDED_DIR/jws-jmx-exporter-config.yaml" /opt/jboss/container/prometheus/etc/jws-jmx-exporter-config.yaml
cp -p "$ADDED_DIR/prometheus-opts" /opt/jboss/container/prometheus/jws-prometheus-opts
