#!/bin/sh
# Prometheus JMX for JWS
set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR="$SCRIPT_DIR/added"

# install prometheus-jmx-exporter
dnf install -y prometheus-jmx-exporter
# prometheus-jmx-exporter installs additional unneeded dependencies on jdk8 and jdk17 images, so we remove them
if [ -n "$(yum list installed java-1.8.0-openjdk-devel |grep java-1.8.0-openjdk-devel)" ] || [ -n "$(yum list installed java-17-openjdk-devel |grep java-17-openjdk-devel)" ]; then
    rpm -e --nodeps java-11-openjdk-headless prometheus-jmx-exporter-openjdk11
fi
dnf clean all

# copy the configuration for JWS
mkdir -p /opt/jboss/container/prometheus/etc
cp -p "$ADDED_DIR/jws-jmx-exporter-config.yaml" /opt/jboss/container/prometheus/etc/jws-jmx-exporter-config.yaml
cp -p "$ADDED_DIR/prometheus-opts" /opt/jboss/container/prometheus/jws-prometheus-opts
